precommit: format lint test

format:
    @echo "Formatting ..."
    ruff format
    npx prettier -w *.md

lint:
    @echo "Linting ..."
    pyright
    ruff check

test *args:
    @echo "Testing \"The Book\" ..."
    @# Why first `cd ..`? Because I am tired of Python's weird local import rules.
    @cd .. && python3 -m bootstrap_py.md_tests bootstrap_py/klar_the_book.md {{args}}
