precommit: 
    just format 
    just lint --fix
    just test

format:
    @echo "Formatting ..."
    ruff format
    npx prettier -w *.md ../*.md

lint *args:
    @echo "Linting ..."
    pyright
    ruff check {{args}}

test: test-pytest test-md

test-pytest *args:
    pytest . {{args}}

[positional-arguments]
test-md *args:
    @cd .. && python3 -m bootstrap_py.md_tests bootstrap_py/klar_the_book.md -- "$@"

klarc *args:
    @cd .. && python3 -m bootstrap_py.main {{args}}
